/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DDropdown: typeof import('./../components/DDropdown/index.vue')['default']
    DResult: typeof import('./../components/DResult.vue')['default']
    Dropdown: typeof import('./../components/Dropdown/index.vue')['default']
    DTabs: typeof import('./../components/DTabs/index.vue')['default']
    DUpload: typeof import('./../components/DUpload.vue')['default']
    EditDialog: typeof import('./../components/EditDialog/index.vue')['default']
    EditMenuItemForm: typeof import('./../components/EditMenuItemForm.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Error: typeof import('./../components/Error/index.vue')['default']
    FormItem: typeof import('./../components/EditDialog/FormItem.vue')['default']
    IEpDeleteFilled: typeof import('~icons/ep/delete-filled')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpEditPen: typeof import('~icons/ep/edit-pen')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    Layout: typeof import('./../components/Layout.vue')['default']
    LayoutBase: typeof import('./../components/LayoutBase/index.vue')['default']
    MenuTag: typeof import('./../components/MenuTag/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../components/sidebar/index.vue')['default']
    Tree: typeof import('./../components/Tree/index.vue')['default']
  }
}
